### ISSUE TITLE
Maximum call stack exceeded on a large Elm Record

### ISSUE THREAD

**Issue by ryan-senn** [pablohirafuji/elm-syntax-highlight#7] opened 2018-08-03 01:55 UTC
Hello,

I tried using this package in a somewhat unconventional way, essentially I am using it to highlight an elm Record (so not source code). When run on larger strings, my browser throws an exception telling me that the maximum call stack is exceeded. I've pasted the record that I'm trying to parse at the end of this message. Here is a demo of what I tried to use it for (leave everything as is and hit submit): https://ryan-senn.github.io/stellar-elm/#/endpoints/all-effects

Essentially I want to highlight a json response parsed to an elm record.

Please let me know if I can help in any way, as I ended up using javascript instead, and I would obviously prefer to use elm for this :)

```Ok (Success { embedded_ = { records = [AccountCreated { id = "0000010157597659137-0000000001" , pagingToken = "10157597659137-1" , type_ = "account_created" , typeI = 0 , account = "GBS43BF24ENNS3KPACUZVKK2VYPOZVBQO2CISGZ777RYGOPYC2FT6S3K" , startingBalance = "50000000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659137" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659137-1" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659137-1" , templated = False } } } ,AccountDebited { id = "0000010157597659137-0000000002" , pagingToken = "10157597659137-2" , type_ = "account_debited" , typeI = 3 , account = "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H" , assetType = Native , amount = "50000000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659137" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659137-2" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659137-2" , templated = False } } } ,SignerCreated { id = "0000010157597659137-0000000003" , pagingToken = "10157597659137-3" , type_ = "signer_created" , typeI = 10 , account = "GBS43BF24ENNS3KPACUZVKK2VYPOZVBQO2CISGZ777RYGOPYC2FT6S3K" , weight = 1 , publicKey = "GBS43BF24ENNS3KPACUZVKK2VYPOZVBQO2CISGZ777RYGOPYC2FT6S3K" , key = "" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659137" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659137-3" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659137-3" , templated = False } } } ,AccountCreated { id = "0000010157597659138-0000000001" , pagingToken = "10157597659138-1" , type_ = "account_created" , typeI = 0 , account = "GDO34SQXVOSNODK7JCTAXLZUPSAF3JIH4ADQELVIKOQJUWQ3U4BMSCSH" , startingBalance = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659138" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659138-1" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659138-1" , templated = False } } } ,AccountDebited { id = "0000010157597659138-0000000002" , pagingToken = "10157597659138-2" , type_ = "account_debited" , typeI = 3 , account = "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H" , assetType = Native , amount = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659138" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659138-2" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659138-2" , templated = False } } } ,SignerCreated { id = "0000010157597659138-0000000003" , pagingToken = "10157597659138-3" , type_ = "signer_created" , typeI = 10 , account = "GDO34SQXVOSNODK7JCTAXLZUPSAF3JIH4ADQELVIKOQJUWQ3U4BMSCSH" , weight = 1 , publicKey = "GDO34SQXVOSNODK7JCTAXLZUPSAF3JIH4ADQELVIKOQJUWQ3U4BMSCSH" , key = "" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659138" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659138-3" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659138-3" , templated = False } } } ,AccountCreated { id = "0000010157597659139-0000000001" , pagingToken = "10157597659139-1" , type_ = "account_created" , typeI = 0 , account = "GAAJKG3WQKHWZJ5RGVVZMVV6X3XYU7QUH2YVATQ2KBVR2ZJYLG35Z65A" , startingBalance = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659139" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659139-1" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659139-1" , templated = False } } } ,AccountDebited { id = "0000010157597659139-0000000002" , pagingToken = "10157597659139-2" , type_ = "account_debited" , typeI = 3 , account = "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H" , assetType = Native , amount = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659139" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659139-2" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659139-2" , templated = False } } } ,SignerCreated { id = "0000010157597659139-0000000003" , pagingToken = "10157597659139-3" , type_ = "signer_created" , typeI = 10 , account = "GAAJKG3WQKHWZJ5RGVVZMVV6X3XYU7QUH2YVATQ2KBVR2ZJYLG35Z65A" , weight = 1 , publicKey = "GAAJKG3WQKHWZJ5RGVVZMVV6X3XYU7QUH2YVATQ2KBVR2ZJYLG35Z65A" , key = "" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659139" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659139-3" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659139-3" , templated = False } } } ,AccountCreated { id = "0000010157597659140-0000000001" , pagingToken = "10157597659140-1" , type_ = "account_created" , typeI = 0 , account = "GCNP7JE6KR5CKHMVVFTZJUSP7ALAXWP62SK6IMIY4IF3JCHEZKBJKDZF" , startingBalance = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659140" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659140-1" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659140-1" , templated = False } } } ,AccountDebited { id = "0000010157597659140-0000000002" , pagingToken = "10157597659140-2" , type_ = "account_debited" , typeI = 3 , account = "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H" , assetType = Native , amount = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659140" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659140-2" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659140-2" , templated = False } } } ,SignerCreated { id = "0000010157597659140-0000000003" , pagingToken = "10157597659140-3" , type_ = "signer_created" , typeI = 10 , account = "GCNP7JE6KR5CKHMVVFTZJUSP7ALAXWP62SK6IMIY4IF3JCHEZKBJKDZF" , weight = 1 , publicKey = "GCNP7JE6KR5CKHMVVFTZJUSP7ALAXWP62SK6IMIY4IF3JCHEZKBJKDZF" , key = "" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659140" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659140-3" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659140-3" , templated = False } } } ,AccountCreated { id = "0000010157597659141-0000000001" , pagingToken = "10157597659141-1" , type_ = "account_created" , typeI = 0 , account = "GDNFUWF2EO4OWXYLI4TDEH4DXUCN6PB24R6XQW4VATORK6WGMHGRXJVB" , startingBalance = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659141" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659141-1" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659141-1" , templated = False } } } ,AccountDebited { id = "0000010157597659141-0000000002" , pagingToken = "10157597659141-2" , type_ = "account_debited" , typeI = 3 , account = "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H" , assetType = Native , amount = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659141" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659141-2" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659141-2" , templated = False } } } ,SignerCreated { id = "0000010157597659141-0000000003" , pagingToken = "10157597659141-3" , type_ = "signer_created" , typeI = 10 , account = "GDNFUWF2EO4OWXYLI4TDEH4DXUCN6PB24R6XQW4VATORK6WGMHGRXJVB" , weight = 1 , publicKey = "GDNFUWF2EO4OWXYLI4TDEH4DXUCN6PB24R6XQW4VATORK6WGMHGRXJVB" , key = "" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659141" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659141-3" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659141-3" , templated = False } } } ] } , links_ = { self = { href = "https://horizon-testnet.stellar.org/effects?cursor=&limit=15&order=asc" , templated = False } , prev = { href = "https://horizon-testnet.stellar.org/effects?cursor=10157597659137-1&limit=15&order=desc" , templated = False } , next = { href = "https://horizon-testnet.stellar.org/effects?cursor=10157597659141-3&limit=15&order=asc" , templated = False } } } )Ok (Success { embedded_ = { records = [AccountCreated { id = "0000010157597659137-0000000001" , pagingToken = "10157597659137-1" , type_ = "account_created" , typeI = 0 , account = "GBS43BF24ENNS3KPACUZVKK2VYPOZVBQO2CISGZ777RYGOPYC2FT6S3K" , startingBalance = "50000000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659137" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659137-1" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659137-1" , templated = False } } } ,AccountDebited { id = "0000010157597659137-0000000002" , pagingToken = "10157597659137-2" , type_ = "account_debited" , typeI = 3 , account = "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H" , assetType = Native , amount = "50000000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659137" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659137-2" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659137-2" , templated = False } } } ,SignerCreated { id = "0000010157597659137-0000000003" , pagingToken = "10157597659137-3" , type_ = "signer_created" , typeI = 10 , account = "GBS43BF24ENNS3KPACUZVKK2VYPOZVBQO2CISGZ777RYGOPYC2FT6S3K" , weight = 1 , publicKey = "GBS43BF24ENNS3KPACUZVKK2VYPOZVBQO2CISGZ777RYGOPYC2FT6S3K" , key = "" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659137" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659137-3" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659137-3" , templated = False } } } ,AccountCreated { id = "0000010157597659138-0000000001" , pagingToken = "10157597659138-1" , type_ = "account_created" , typeI = 0 , account = "GDO34SQXVOSNODK7JCTAXLZUPSAF3JIH4ADQELVIKOQJUWQ3U4BMSCSH" , startingBalance = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659138" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659138-1" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659138-1" , templated = False } } } ,AccountDebited { id = "0000010157597659138-0000000002" , pagingToken = "10157597659138-2" , type_ = "account_debited" , typeI = 3 , account = "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H" , assetType = Native , amount = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659138" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659138-2" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659138-2" , templated = False } } } ,SignerCreated { id = "0000010157597659138-0000000003" , pagingToken = "10157597659138-3" , type_ = "signer_created" , typeI = 10 , account = "GDO34SQXVOSNODK7JCTAXLZUPSAF3JIH4ADQELVIKOQJUWQ3U4BMSCSH" , weight = 1 , publicKey = "GDO34SQXVOSNODK7JCTAXLZUPSAF3JIH4ADQELVIKOQJUWQ3U4BMSCSH" , key = "" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659138" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659138-3" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659138-3" , templated = False } } } ,AccountCreated { id = "0000010157597659139-0000000001" , pagingToken = "10157597659139-1" , type_ = "account_created" , typeI = 0 , account = "GAAJKG3WQKHWZJ5RGVVZMVV6X3XYU7QUH2YVATQ2KBVR2ZJYLG35Z65A" , startingBalance = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659139" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659139-1" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659139-1" , templated = False } } } ,AccountDebited { id = "0000010157597659139-0000000002" , pagingToken = "10157597659139-2" , type_ = "account_debited" , typeI = 3 , account = "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H" , assetType = Native , amount = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659139" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659139-2" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659139-2" , templated = False } } } ,SignerCreated { id = "0000010157597659139-0000000003" , pagingToken = "10157597659139-3" , type_ = "signer_created" , typeI = 10 , account = "GAAJKG3WQKHWZJ5RGVVZMVV6X3XYU7QUH2YVATQ2KBVR2ZJYLG35Z65A" , weight = 1 , publicKey = "GAAJKG3WQKHWZJ5RGVVZMVV6X3XYU7QUH2YVATQ2KBVR2ZJYLG35Z65A" , key = "" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659139" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659139-3" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659139-3" , templated = False } } } ,AccountCreated { id = "0000010157597659140-0000000001" , pagingToken = "10157597659140-1" , type_ = "account_created" , typeI = 0 , account = "GCNP7JE6KR5CKHMVVFTZJUSP7ALAXWP62SK6IMIY4IF3JCHEZKBJKDZF" , startingBalance = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659140" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659140-1" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659140-1" , templated = False } } } ,AccountDebited { id = "0000010157597659140-0000000002" , pagingToken = "10157597659140-2" , type_ = "account_debited" , typeI = 3 , account = "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H" , assetType = Native , amount = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659140" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659140-2" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659140-2" , templated = False } } } ,SignerCreated { id = "0000010157597659140-0000000003" , pagingToken = "10157597659140-3" , type_ = "signer_created" , typeI = 10 , account = "GCNP7JE6KR5CKHMVVFTZJUSP7ALAXWP62SK6IMIY4IF3JCHEZKBJKDZF" , weight = 1 , publicKey = "GCNP7JE6KR5CKHMVVFTZJUSP7ALAXWP62SK6IMIY4IF3JCHEZKBJKDZF" , key = "" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659140" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659140-3" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659140-3" , templated = False } } } ,AccountCreated { id = "0000010157597659141-0000000001" , pagingToken = "10157597659141-1" , type_ = "account_created" , typeI = 0 , account = "GDNFUWF2EO4OWXYLI4TDEH4DXUCN6PB24R6XQW4VATORK6WGMHGRXJVB" , startingBalance = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659141" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659141-1" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659141-1" , templated = False } } } ,AccountDebited { id = "0000010157597659141-0000000002" , pagingToken = "10157597659141-2" , type_ = "account_debited" , typeI = 3 , account = "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H" , assetType = Native , amount = "10000.0000000" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659141" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659141-2" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659141-2" , templated = False } } } ,SignerCreated { id = "0000010157597659141-0000000003" , pagingToken = "10157597659141-3" , type_ = "signer_created" , typeI = 10 , account = "GDNFUWF2EO4OWXYLI4TDEH4DXUCN6PB24R6XQW4VATORK6WGMHGRXJVB" , weight = 1 , publicKey = "GDNFUWF2EO4OWXYLI4TDEH4DXUCN6PB24R6XQW4VATORK6WGMHGRXJVB" , key = "" , createdAt = <Tue Mar 21 2017 05:50:52 GMT+1000 (Australian Eastern Standard Time )> , links = { operation = { href = "https://horizon-testnet.stellar.org/operations/10157597659141" , templated = False } , succeeds = { href = "https://horizon-testnet.stellar.org/effects?order=desc&cursor=10157597659141-3" , templated = False } , precedes = { href = "https://horizon-testnet.stellar.org/effects?order=asc&cursor=10157597659141-3" , templated = False } } } ] } , links_ = { self = { href = "https://horizon-testnet.stellar.org/effects?cursor=&limit=15&order=asc" , templated = False } , prev = { href = "https://horizon-testnet.stellar.org/effects?cursor=10157597659137-1&limit=15&order=desc" , templated = False } , next = { href = "https://horizon-testnet.stellar.org/effects?cursor=10157597659141-3&limit=15&order=asc" , templated = False } } } )Ω```

**Comment by pablohirafuji** [comment] 2018-08-03 08:29
Hey, I did some tests and the problem is that the parser has problem with really long lines. If you can do some preprocessing for now, like inserting some line breaks (`\n`) along the way, it will parse fine. Thanks for the report, I will take another approach while updating to 0.19 in order to avoid this issue. Can't promise any improvements for the 0.18 though.

**Comment by pablohirafuji** [comment] 2018-09-23 02:40
Fixed in the 0.19 version. Thanks for the feedback!

**Closed as completed by pablohirafuji** 2018-09-23 02:40 UTC
